MODULE = wifi_pro
SRC = wifi_pro.c

CFLAGS += -DESP32S3 -DMP_CONFIG_ESP32_SPIRAM -DCONFIG_SPIRAM_MODE_OCT=1
CFLAGS += -I$(TOP)

PROJECT_DIR ?= $(CURDIR)
USER_C_MODULES += $(PROJECT_DIR)/user_c_modules/$(MODULE)