name: Build YasuPython Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Build Script
          # Ensure build.sh is executable in the repo or chmod it here
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YasuPython-ESP32S3-N16R8
          path: micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/firmware.bin
          if-no-files-found: error
          retention-days: 7